### ISSUE TITLE
On the send page, cannot type in token amount and the balance is always 100

### ISSUE THREAD

**Issue by troyrocket** [Move-Stream/moveflow#8]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/105162534/221386619-9db71961-fa00-4eed-9047-8fbf6ba68811.png">

need to correct the input and show real wallet balance.

**Comment by livelybug** [comment]
https://github.com/Move-Stream/streampay-frontend/commit/dbb5ab2f882896488e403928a2a7bad8086f1633

**Comment by livelybug** [comment]
https://github.com/Move-Stream/streampay-frontend/commits/incorrect-balance-send-page
